### ISSUE TITLE
Build fails: error: use of undeclared identifier 'get_current_dir_name'

### ISSUE THREAD

**Issue by njaupan** [lxwgcool/CircDBG#1]
Hi,
I have tried to install in the Mac OSX but it gets build error:
g++ -O3 -Wall -std=c++0x -c ../../ShareLibrary/clsbwa.cpp
../../ShareLibrary/clsbwa.cpp:11:48: error: use of undeclared identifier 'get_current_dir_name'
    string strRootPath = ::GetHigherFolderPath(get_current_dir_name());
                                               ^
../../ShareLibrary/clsbwa.cpp:110:46: error: use of undeclared identifier 'get_current_dir_name'
    string strRootPath = GetHigherFolderPath(get_current_dir_name());
                                             ^
../../ShareLibrary/clsbwa.cpp:113:33: error: use of undeclared identifier 'get_current_dir_name'
    cout << GetHigherFolderPath(get_current_dir_name()) << endl;
   
Do you know how to fix it?
Best regards

**Comment by lxwgcool** [comment]
Dear Ivy,

Thank you so much for using CircDBG. The makefile provided by CircDBG is
for Linux (such as redhat, ubuntu and centos) rather than Mac. Can you find
a Linux machine and run CircDBG on it?

Sorry for this inconvenience.
Best regards
Xin


Ivy <notifications@github.com> 于2020年5月7日周四 下午2:42写道：

**Comment by njaupan** [comment]
Thank you for the quick reply. However, I neither have root in Cluster ubuntu system nor linux laptop. Do you have version that can install by Conda?

**Comment by lxwgcool** [comment]
Hi Ivy,

You do not have to be root in Linux system. CircDBG can be compiled without
root. Simply use git to get source code and use make to compile it. The
executable file will be generated in the same folder after "make" be
finished. You do not need to run "make install".
Once you get such executable binary file, you can use it directly to
analysis your data.

Please let me know if you have any questions.
Best
Xin

Ivy <notifications@github.com> 于2020年5月7日周四 下午5:16写道：

**Comment by lxwgcool** [comment]
It should be all set
